import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
  presets: [presetUno()],
  shortcuts: {
    'auth-shell': 'h-screen min-h-0 grid place-items-center p-7 lt-sm:p-4',
    'auth-card': 'grid gap-[22px] w-[min(480px,100%)] p-6 lt-sm:p-[22px]',
    'auth-card--settings': 'w-[min(960px,100%)] max-h-[calc(100vh-56px)] overflow-auto',
    'auth-error': 'grid gap-2.5',
    'auth-error__actions': 'flex flex-wrap gap-2',
    'auth-brand': 'flex items-center gap-3.5',
    'auth-brand__mark': 'grid place-items-center w-11 h-11 rounded text-[1.55rem] font-700 text-[rgb(var(--v-theme-on-primary))] bg-[rgb(var(--v-theme-primary))]',
    'auth-brand__title': 'm-0 text-[1.18rem]',
    'auth-brand__subtitle': 'm-0 mt-[5px] text-[0.86rem] text-[rgba(var(--v-theme-on-surface),0.68)]',
    'client-shell': 'h-screen min-h-0 grid grid-cols-[88px_minmax(0,1fr)] lt-md:grid-cols-1 lt-md:grid-rows-[1fr_auto]',
    'client-rail': 'sticky top-0 grid grid-rows-[auto_1fr_auto] gap-5 h-screen py-4 px-2.5 bg-[rgb(var(--v-theme-surface))] border-r border-[rgba(var(--v-border-color),var(--v-border-opacity))] lt-md:fixed lt-md:right-3 lt-md:bottom-3 lt-md:left-3 lt-md:top-auto lt-md:z-30 lt-md:grid-rows-none lt-md:grid-cols-1 lt-md:h-[76px] lt-md:p-2 lt-md:border',
    'client-rail__brand': 'grid place-items-center justify-self-center w-[46px] h-[46px] rounded font-700 text-[1.5rem] text-[rgb(var(--v-theme-on-primary))] bg-[rgb(var(--v-theme-primary))] lt-md:hidden',
    'client-rail__account': 'grid place-items-center justify-self-center w-[46px] h-[46px] rounded font-700 bg-[rgb(var(--v-theme-surface-variant))] lt-md:hidden',
    'client-rail__items': 'grid content-start gap-2 lt-md:grid-cols-2 lt-md:gap-1',
    'rail-destination': 'justify-self-center w-[66px] h-[58px] tracking-0 normal-case lt-md:w-full lt-md:h-[60px]',
    'client-workspace': 'grid grid-rows-[auto_1fr] h-screen min-w-0 min-h-0',
    'client-topbar': 'sticky top-0 z-10 grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 min-h-[72px] px-6 border-b border-[rgba(var(--v-border-color),var(--v-border-opacity))] lt-md:px-[18px] lt-sm:min-h-[66px]',
    'client-topbar__title': 'min-w-0',
    'client-page': 'w-full max-w-[1520px] min-w-0 min-h-0 px-6 pt-5 pb-7 overflow-auto lt-md:p-3.5 lt-md:pb-[104px] lt-sm:p-4',
    'client-error': 'mb-3.5',
    'player-shell': 'h-screen min-h-0 p-3 overflow-hidden bg-black lt-md:p-3.5',
    'section-kicker': 'm-0 mb-1.5 text-[0.72rem] font-500 tracking-[0.04em] uppercase text-[rgb(var(--v-theme-primary))]',
    'section-title': 'm-0 text-[1.28rem] font-500 leading-[1.22] [overflow-wrap:anywhere]',
    'is-loading-line': 'relative overflow-hidden',
    'history-card': 'grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-2 border-transparent p-2.5 lt-md:grid-cols-1',
    'history-card--active': 'border-[rgb(var(--v-theme-primary))]',
    'history-card__main': 'grid grid-cols-[72px_minmax(0,1fr)] gap-3 min-w-0 border-0 bg-transparent p-0 text-left text-inherit cursor-pointer lt-md:grid-cols-[64px_minmax(0,1fr)]',
    'history-card__poster': 'relative grid aspect-[16/10] place-items-center overflow-hidden bg-[rgba(var(--v-theme-on-surface),0.08)] text-[rgba(var(--v-theme-on-surface),0.68)]',
    'history-card__image': 'h-full w-full object-cover',
    'history-card__played': 'absolute right-1.5 top-1.5 grid h-[22px] w-[22px] place-items-center rounded bg-[rgb(var(--v-theme-primary))] text-[rgb(var(--v-theme-on-primary))]',
    'history-card__body': 'grid gap-[5px] min-w-0',
    'history-card__title': 'text-[0.98rem] font-500 leading-[1.25] [overflow-wrap:anywhere]',
    'history-card__meta': 'text-[0.8rem] leading-[1.3] text-[rgba(var(--v-theme-on-surface),0.68)] [overflow-wrap:anywhere]',
    'history-card__progress-label': 'text-[0.8rem] leading-[1.3] text-[rgba(var(--v-theme-on-surface),0.72)] [overflow-wrap:anywhere]',
    'history-card__progress': 'block h-1 w-[min(280px,100%)] overflow-hidden bg-[rgba(var(--v-theme-on-surface),0.18)]',
    'history-card__progress-fill': 'block h-full bg-[rgb(var(--v-theme-primary))]',
    'history-card__actions': 'flex justify-end lt-md:justify-start',
    'playback-history-view': 'grid content-start gap-[18px] min-w-0',
    'history-hero': 'p-5',
    'history-hero__title': 'm-0 text-[clamp(1.18rem,1.8vw,1.55rem)] font-500 leading-[1.18]',
    'history-hero__copy': 'm-0 mt-[7px] max-w-[46rem] text-[0.9rem] leading-[1.55] text-[rgba(var(--v-theme-on-surface),0.68)]',
    'history-filters': 'flex flex-wrap gap-2',
    'history-filters__chip': 'cursor-pointer',
    'history-section': 'grid gap-3 min-w-0',
    'history-section__heading': 'flex items-end justify-between gap-4',
    'history-section__title': 'm-0 text-[clamp(1.18rem,1.8vw,1.55rem)] font-500 leading-[1.18]',
    'history-section__count': 'text-[0.84rem] text-[rgba(var(--v-theme-on-surface),0.6)]',
    'history-list': 'grid gap-2.5',
    'history-load-more': 'flex justify-center pb-2 pt-1',
    'history-empty': 'grid min-h-[220px] place-items-center content-center gap-3 text-[rgba(var(--v-theme-on-surface),0.68)]',
    'history-empty--compact': 'min-h-[140px]',
    'history-dialog': 'grid gap-3 p-[18px]',
    'history-dialog__title': 'm-0 text-[1.12rem] font-500 leading-[1.25]',
    'history-dialog__copy': 'm-0 text-[0.9rem] leading-[1.45] text-[rgba(var(--v-theme-on-surface),0.68)] [overflow-wrap:anywhere]',
    'history-dialog__actions': 'flex justify-end gap-2',
  },
})
